version: "3.8"

services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - database_dbadmin
      - api_database
    volumes:
      - db:/data/db

  weather_api:
    depends_on:
      - mongo_db
    build: ./weather_api
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - api_database
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
        }'

  mongo_express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - $MONGO_EXPRESS_LOCAL_PORT:$MONGO_EXPRESS_DOCKER_PORT
    networks:
      - database_dbadmin
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $MONGODB_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongo_db

volumes:
  db:
    driver: local

networks:
  api_database:
    driver: bridge
  database_dbadmin:
    driver: bridge